# Generated by Django 4.2.2 on 2023-06-24 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_alter_analysis_result_alter_analysis_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
